<?php

use Illuminate\Database\Seeder;

class RacesSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('races')->insert([
			/*
			 * Dogs
			*/
			['id' => '1', 'name' => 'Affenpinscher', 'animal_id' => '1'],
			['id' => '2', 'name' => 'Airedale terrier', 'animal_id' => '1'],
			['id' => '3', 'name' => 'Aïdi', 'animal_id' => '1'],
			['id' => '4', 'name' => 'Akita Inu', 'animal_id' => '1'],
			['id' => '5', 'name' => 'Akita Americano', 'animal_id' => '1'],
			['id' => '6', 'name' => 'Alano español', 'animal_id' => '1'],
			['id' => '7', 'name' => 'Alaskan malamute', 'animal_id' => '1'],
			['id' => '8', 'name' => 'Alaskan Klee Kai', 'animal_id' => '1'],
			['id' => '9', 'name' => 'American Hairless terrier', 'animal_id' => '1'],
			['id' => '10', 'name' => 'American Staffordshire Terrier', 'animal_id' => '1'],
			['id' => '11', 'name' => 'Antiguo Perro Pastor Inglés', 'animal_id' => '1'],
			['id' => '12', 'name' => 'Appenzeller', 'animal_id' => '1'],
			['id' => '13', 'name' => 'Australian Cattle Dog', 'animal_id' => '1'],
			['id' => '14', 'name' => 'Australian terrier', 'animal_id' => '1'],
			['id' => '15', 'name' => 'Australian Silky Terrier', 'animal_id' => '1'],
			['id' => '16', 'name' => 'Azawakh', 'animal_id' => '1'],
			['id' => '17', 'name' => 'Bardino (Perro majorero)', 'animal_id' => '1'],
			['id' => '18', 'name' => 'Basenji', 'animal_id' => '1'],
			['id' => '19', 'name' => 'Basset azul de Gascuña', 'animal_id' => '1'],
			['id' => '20', 'name' => 'Basset hound', 'animal_id' => '1'],
			['id' => '21', 'name' => 'Beagle', 'animal_id' => '1'],
			['id' => '22', 'name' => 'Beauceron', 'animal_id' => '1'],
			['id' => '23', 'name' => 'Bedlington terrier', 'animal_id' => '1'],
			['id' => '24', 'name' => 'Bergamasco', 'animal_id' => '1'],
			['id' => '25', 'name' => 'Bichon frisé', 'animal_id' => '1'],
			['id' => '26', 'name' => 'Bichón maltés', 'animal_id' => '1'],
			['id' => '27', 'name' => 'Bichón habanero', 'animal_id' => '1'],
			['id' => '28', 'name' => 'Bobtail', 'animal_id' => '1'],
			['id' => '29', 'name' => 'Bloodhound', 'animal_id' => '1'],
			['id' => '30', 'name' => 'Border collie', 'animal_id' => '1'],
			['id' => '31', 'name' => 'Borzoi', 'animal_id' => '1'],
			['id' => '32', 'name' => 'Boston terrier', 'animal_id' => '1'],
			['id' => '33', 'name' => 'Bóxer', 'animal_id' => '1'],
			['id' => '34', 'name' => 'Boyero de Berna', 'animal_id' => '1'],
			['id' => '35', 'name' => 'Boyero de Flandes', 'animal_id' => '1'],
			['id' => '36', 'name' => 'Braco alemán de pelo corto', 'animal_id' => '1'],
			['id' => '37', 'name' => 'Braco alemán de pelo duro', 'animal_id' => '1'],
			['id' => '38', 'name' => 'Braco de Auvernia', 'animal_id' => '1'],
			['id' => '39', 'name' => 'Braco francés', 'animal_id' => '1'],
			['id' => '40', 'name' => 'Braco húngaro', 'animal_id' => '1'],
			['id' => '41', 'name' => 'Braco italiano', 'animal_id' => '1'],
			['id' => '42', 'name' => 'Braco tirolés', 'animal_id' => '1'],
			['id' => '43', 'name' => 'Braco de Saint Germain', 'animal_id' => '1'],
			['id' => '44', 'name' => 'Braco de Weimar', 'animal_id' => '1'],
			['id' => '45', 'name' => 'Bull Terrier', 'animal_id' => '1'],
			['id' => '46', 'name' => 'Bulldog americano', 'animal_id' => '1'],
			['id' => '47', 'name' => 'Bulldog francés', 'animal_id' => '1'],
			['id' => '48', 'name' => 'Bulldog inglés', 'animal_id' => '1'],
			['id' => '49', 'name' => 'Bullmastiff', 'animal_id' => '1'],
			['id' => '50', 'name' => 'Buhund noruego', 'animal_id' => '1'],
			['id' => '51', 'name' => 'Can de palleiro', 'animal_id' => '1'],
			['id' => '52', 'name' => 'Caniche', 'animal_id' => '1'],
			['id' => '53', 'name' => 'Cão da Serra da Estrela', 'animal_id' => '1'],
			['id' => '54', 'name' => 'Cão da Serra de Aires', 'animal_id' => '1'],
			['id' => '55', 'name' => 'Cão de Agua Português', 'animal_id' => '1'],
			['id' => '56', 'name' => 'Cão de Castro Laboreiro', 'animal_id' => '1'],
			['id' => '57', 'name' => 'Cão de Fila de São Miguel', 'animal_id' => '1'],
			['id' => '58', 'name' => 'Cavalier King Charles Spaniel', 'animal_id' => '1'],
			['id' => '59', 'name' => 'Cazador de alces noruego', 'animal_id' => '1'],
			['id' => '60', 'name' => 'Chesapeake Bay Retriever', 'animal_id' => '1'],
			['id' => '61', 'name' => 'Chihuahueño', 'animal_id' => '1'],
			['id' => '62', 'name' => 'Crestado Chino', 'animal_id' => '1'],
			['id' => '63', 'name' => 'Cimarrón Uruguayo', 'animal_id' => '1'],
			['id' => '64', 'name' => 'Cirneco del Etna', 'animal_id' => '1'],
			['id' => '65', 'name' => 'Chow chow', 'animal_id' => '1'],
			['id' => '66', 'name' => 'Clumber spaniel', 'animal_id' => '1'],
			['id' => '67', 'name' => 'Cobrador de pelo liso', 'animal_id' => '1'],
			['id' => '68', 'name' => 'Cocker spaniel americano', 'animal_id' => '1'],
			['id' => '69', 'name' => 'Cocker spaniel inglés', 'animal_id' => '1'],
			['id' => '70', 'name' => 'Collie de pelo corto', 'animal_id' => '1'],
			['id' => '71', 'name' => 'Collie de pelo largo', 'animal_id' => '1'],
			['id' => '72', 'name' => 'Bearded collie', 'animal_id' => '1'],
			['id' => '73', 'name' => 'Corgi galés de Cardigan', 'animal_id' => '1'],
			['id' => '74', 'name' => 'Dachshund', 'animal_id' => '1'],
			['id' => '75', 'name' => 'Dálmata', 'animal_id' => '1'],
			['id' => '76', 'name' => 'Dandie Dinmont Terrier', 'animal_id' => '1'],
			['id' => '77', 'name' => 'Deerhound', 'animal_id' => '1'],
			['id' => '78', 'name' => 'Dobermann', 'animal_id' => '1'],
			['id' => '79', 'name' => 'Dogo alemán', 'animal_id' => '1'],
			['id' => '80', 'name' => 'Dogo argentino', 'animal_id' => '1'],
			['id' => '81', 'name' => 'Dogo de burdeos', 'animal_id' => '1'],
			['id' => '82', 'name' => 'Dogo del Tíbet', 'animal_id' => '1'],
			['id' => '83', 'name' => 'Dogo guatemalteco', 'animal_id' => '1'],
			['id' => '84', 'name' => 'English springer spaniel', 'animal_id' => '1'],
			['id' => '85', 'name' => 'Entlebucher', 'animal_id' => '1'],
			['id' => '86', 'name' => 'Épagneul bretón', 'animal_id' => '1'],
			['id' => '87', 'name' => 'Épagneul français', 'animal_id' => '1'],
			['id' => '88', 'name' => 'Epagneul papillón', 'animal_id' => '1'],
			['id' => '89', 'name' => 'Eurasier', 'animal_id' => '1'],
			['id' => '90', 'name' => 'Fila Brasileiro', 'animal_id' => '1'],
			['id' => '91', 'name' => 'Flat-Coated Retriever', 'animal_id' => '1'],
			['id' => '92', 'name' => 'Fox Terrier', 'animal_id' => '1'],
			['id' => '93', 'name' => 'Foxhound americano', 'animal_id' => '1'],
			['id' => '94', 'name' => 'Galgo español', 'animal_id' => '1'],
			['id' => '95', 'name' => 'Galgo húngaro', 'animal_id' => '1'],
			['id' => '96', 'name' => 'Galgo inglés', 'animal_id' => '1'],
			['id' => '97', 'name' => 'Galgo italiano', 'animal_id' => '1'],
			['id' => '98', 'name' => 'Golden retriever', 'animal_id' => '1'],
			['id' => '99', 'name' => 'Glen of Imaal Terrier', 'animal_id' => '1'],
			['id' => '100', 'name' => 'Gran danés', 'animal_id' => '1'],
			['id' => '101', 'name' => 'Gegar colombiano', 'animal_id' => '1'],
			['id' => '102', 'name' => 'Greyhound', 'animal_id' => '1'],
			['id' => '103', 'name' => 'Grifón belga', 'animal_id' => '1'],
			['id' => '104', 'name' => 'Hovawart', 'animal_id' => '1'],
			['id' => '105', 'name' => 'Husky siberiano', 'animal_id' => '1'],
			['id' => '106', 'name' => 'Jack Russell Terrier', 'animal_id' => '1'],
			['id' => '107', 'name' => 'Keeshond', 'animal_id' => '1'],
			['id' => '108', 'name' => 'Kerry blue terrier', 'animal_id' => '1'],
			['id' => '109', 'name' => 'Komondor', 'animal_id' => '1'],
			['id' => '110', 'name' => 'Kuvasz', 'animal_id' => '1'],
			['id' => '111', 'name' => 'Labrador', 'animal_id' => '1'],
			['id' => '112', 'name' => 'Lakeland Terrier', 'animal_id' => '1'],
			['id' => '113', 'name' => 'Laekenois', 'animal_id' => '1'],
			['id' => '114', 'name' => 'Landseer', 'animal_id' => '1'],
			['id' => '115', 'name' => 'Lebrel afgano', 'animal_id' => '1'],
			['id' => '116', 'name' => 'Lebrel polaco', 'animal_id' => '1'],
			['id' => '117', 'name' => 'Leonberger', 'animal_id' => '1'],
			['id' => '118', 'name' => 'Lobero irlandés', 'animal_id' => '1'],
			['id' => '119', 'name' => 'Lundehund', 'animal_id' => '1'],
			['id' => '120', 'name' => 'Perro lobo de Saarloos', 'animal_id' => '1'],
			['id' => '121', 'name' => 'Lhasa apso', 'animal_id' => '1'],
			['id' => '122', 'name' => 'Löwchen', 'animal_id' => '1'],
			['id' => '123', 'name' => 'Maltés', 'animal_id' => '1'],
			['id' => '124', 'name' => 'Malinois', 'animal_id' => '1'],
			['id' => '125', 'name' => 'Manchester terrier', 'animal_id' => '1'],
			['id' => '126', 'name' => 'Mastín afgano', 'animal_id' => '1'],
			['id' => '127', 'name' => 'Mastín del Pirineo', 'animal_id' => '1'],
			['id' => '128', 'name' => 'Mastín español', 'animal_id' => '1'],
			['id' => '129', 'name' => 'Mastín inglés', 'animal_id' => '1'],
			['id' => '130', 'name' => 'Mastín italiano', 'animal_id' => '1'],
			['id' => '131', 'name' => 'Mastín napolitano', 'animal_id' => '1'],
			['id' => '132', 'name' => 'Mastín tibetano', 'animal_id' => '1'],
			['id' => '133', 'name' => 'Mucuchies', 'animal_id' => '1'],
			['id' => '134', 'name' => 'Mudi', 'animal_id' => '1'],
			['id' => '135', 'name' => 'Münsterländer grande', 'animal_id' => '1'],
			['id' => '136', 'name' => 'Münsterländer pequeño', 'animal_id' => '1'],
			['id' => '137', 'name' => 'Nova Scotia Duck Tolling Retriever', 'animal_id' => '1'],
			['id' => '138', 'name' => 'Ovejero magallánico', 'animal_id' => '1'],
			['id' => '139', 'name' => 'Pastor alemán', 'animal_id' => '1'],
			['id' => '140', 'name' => 'Pastor belga', 'animal_id' => '1'],
			['id' => '141', 'name' => 'Pastor blanco suizo', 'animal_id' => '1'],
			['id' => '142', 'name' => 'Pastor catalán', 'animal_id' => '1'],
			['id' => '143', 'name' => 'Pastor croata', 'animal_id' => '1'],
			['id' => '144', 'name' => 'Pastor garafiano', 'animal_id' => '1'],
			['id' => '145', 'name' => 'Pastor holandés', 'animal_id' => '1'],
			['id' => '146', 'name' => 'Pastor peruano Chiribaya', 'animal_id' => '1'],
			['id' => '147', 'name' => 'Pastor de Brie', 'animal_id' => '1'],
			['id' => '148', 'name' => 'Pastor de los Pirineos', 'animal_id' => '1'],
			['id' => '149', 'name' => 'Pastor leonés', 'animal_id' => '1'],
			['id' => '150', 'name' => 'Pastor mallorquín', 'animal_id' => '1'],
			['id' => '151', 'name' => 'Pastor maremmano-abrucés', 'animal_id' => '1'],
			['id' => '152', 'name' => 'Pastor de Valée', 'animal_id' => '1'],
			['id' => '153', 'name' => 'Pastor vasco', 'animal_id' => '1'],
			['id' => '154', 'name' => 'Pekinés', 'animal_id' => '1'],
			['id' => '155', 'name' => 'Pembroke Welsh Corgi', 'animal_id' => '1'],
			['id' => '156', 'name' => 'Pequeño Lebrel Italiano', 'animal_id' => '1'],
			['id' => '157', 'name' => 'Perdiguero francés', 'animal_id' => '1'],
			['id' => '158', 'name' => 'Perdiguero portugués', 'animal_id' => '1'],
			['id' => '159', 'name' => 'Perro cimarrón uruguayo', 'animal_id' => '1'],
			['id' => '160', 'name' => 'Perro de agua americano', 'animal_id' => '1'],
			['id' => '161', 'name' => 'Perro de agua español', 'animal_id' => '1'],
			['id' => '162', 'name' => 'Perro de agua irlandés', 'animal_id' => '1'],
			['id' => '163', 'name' => 'Perro de agua portugués', 'animal_id' => '1'],
			['id' => '164', 'name' => 'Perro de Groenlandia', 'animal_id' => '1'],
			['id' => '165', 'name' => 'Perro de osos de Carelia', 'animal_id' => '1'],
			['id' => '166', 'name' => 'Perro dogo mallorquín', 'animal_id' => '1'],
			['id' => '167', 'name' => 'Perro esquimal canadiense', 'animal_id' => '1'],
			['id' => '168', 'name' => 'Perro de Montaña de los Pirineos', 'animal_id' => '1'],
			['id' => '169', 'name' => 'Perro fino colombiano', 'animal_id' => '1'],
			['id' => '170', 'name' => 'Perro pastor de las islas Shetland', 'animal_id' => '1'],
			['id' => '171', 'name' => 'Perro peruano sin pelo', 'animal_id' => '1'],
			['id' => '172', 'name' => 'Phalène', 'animal_id' => '1'],
			['id' => '173', 'name' => 'Pinscher alemán', 'animal_id' => '1'],
			['id' => '174', 'name' => 'Pinscher miniatura', 'animal_id' => '1'],
			['id' => '175', 'name' => 'Pitbull', 'animal_id' => '1'],
			['id' => '176', 'name' => 'Podenco canario', 'animal_id' => '1'],
			['id' => '177', 'name' => 'Podenco ibicenco', 'animal_id' => '1'],
			['id' => '178', 'name' => 'Podenco portugués', 'animal_id' => '1'],
			['id' => '179', 'name' => 'Pointer', 'animal_id' => '1'],
			['id' => '180', 'name' => 'Pomerania', 'animal_id' => '1'],
			['id' => '181', 'name' => 'Presa canario', 'animal_id' => '1'],
			['id' => '182', 'name' => 'Pudelpointer', 'animal_id' => '1'],
			['id' => '183', 'name' => 'Pug', 'animal_id' => '1'],
			['id' => '184', 'name' => 'Puli', 'animal_id' => '1'],
			['id' => '185', 'name' => 'Pumi', 'animal_id' => '1'],
			['id' => '186', 'name' => 'Rafeiro do Alentejo', 'animal_id' => '1'],
			['id' => '187', 'name' => 'Ratonero bodeguero andaluz', 'animal_id' => '1'],
			['id' => '188', 'name' => 'Ratonero mallorquín', 'animal_id' => '1'],
			['id' => '189', 'name' => 'Ratonero valenciano', 'animal_id' => '1'],
			['id' => '190', 'name' => 'Rhodesian Ridgeback', 'animal_id' => '1'],
			['id' => '191', 'name' => 'Rottweiler', 'animal_id' => '1'],
			['id' => '192', 'name' => 'Saluki', 'animal_id' => '1'],
			['id' => '193', 'name' => 'Samoyedo', 'animal_id' => '1'],
			['id' => '194', 'name' => 'San Bernardo', 'animal_id' => '1'],
			['id' => '195', 'name' => 'Schapendoes', 'animal_id' => '1'],
			['id' => '196', 'name' => 'Schnauzer estándar', 'animal_id' => '1'],
			['id' => '197', 'name' => 'Schnauzer gigante', 'animal_id' => '1'],
			['id' => '198', 'name' => 'Schnauzer miniatura', 'animal_id' => '1'],
			['id' => '199', 'name' => 'Staffordshire Bull Terrier', 'animal_id' => '1'],
			['id' => '200', 'name' => 'Sabueso bosnio', 'animal_id' => '1'],
			['id' => '201', 'name' => 'Schipperke', 'animal_id' => '1'],
			['id' => '202', 'name' => 'Sealyham terrier', 'animal_id' => '1'],
			['id' => '203', 'name' => 'Setter inglés', 'animal_id' => '1'],
			['id' => '204', 'name' => 'Setter irlandés', 'animal_id' => '1'],
			['id' => '205', 'name' => 'Shar Pei', 'animal_id' => '1'],
			['id' => '206', 'name' => 'Shiba Inu', 'animal_id' => '1'],
			['id' => '207', 'name' => 'Shih Tzu', 'animal_id' => '1'],
			['id' => '208', 'name' => 'Shikoku Inu', 'animal_id' => '1'],
			['id' => '209', 'name' => 'Siberian husky', 'animal_id' => '1'],
			['id' => '210', 'name' => 'Skye terrier', 'animal_id' => '1'],
			['id' => '211', 'name' => 'Spaniel japonés', 'animal_id' => '1'],
			['id' => '212', 'name' => 'Spaniel tibetano', 'animal_id' => '1'],
			['id' => '213', 'name' => 'Spitz enano', 'animal_id' => '1'],
			['id' => '214', 'name' => 'Spitz grande', 'animal_id' => '1'],
			['id' => '215', 'name' => 'Spitz mediano', 'animal_id' => '1'],
			['id' => '216', 'name' => 'Spitz japonés', 'animal_id' => '1'],
			['id' => '217', 'name' => 'Sussex spaniel', 'animal_id' => '1'],
			['id' => '218', 'name' => 'Teckel', 'animal_id' => '1'],
			['id' => '219', 'name' => 'Terranova', 'animal_id' => '1'],
			['id' => '220', 'name' => 'Terrier alemán', 'animal_id' => '1'],
			['id' => '221', 'name' => 'Terrier brasileño', 'animal_id' => '1'],
			['id' => '222', 'name' => 'Terrier checo', 'animal_id' => '1'],
			['id' => '223', 'name' => 'Terrier chileno', 'animal_id' => '1'],
			['id' => '224', 'name' => 'Terrier de Norfolk', 'animal_id' => '1'],
			['id' => '225', 'name' => 'Terrier de Norwich', 'animal_id' => '1'],
			['id' => '226', 'name' => 'Terrier escocés', 'animal_id' => '1'],
			['id' => '227', 'name' => 'Terrier galés', 'animal_id' => '1'],
			['id' => '228', 'name' => 'Terrier irlandés', 'animal_id' => '1'],
			['id' => '229', 'name' => 'Terrier ruso negro', 'animal_id' => '1'],
			['id' => '230', 'name' => 'Terrier tibetano', 'animal_id' => '1'],
			['id' => '231', 'name' => 'Toy spaniel inglés', 'animal_id' => '1'],
			['id' => '232', 'name' => 'Tervueren', 'animal_id' => '1'],
			['id' => '233', 'name' => 'Vallhund sueco', 'animal_id' => '1'],
			['id' => '234', 'name' => 'Volpino italiano', 'animal_id' => '1'],
			['id' => '235', 'name' => 'Weimaraner', 'animal_id' => '1'],
			['id' => '236', 'name' => 'West Highland White Terrier', 'animal_id' => '1'],
			['id' => '237', 'name' => 'Whippet', 'animal_id' => '1'],
			['id' => '238', 'name' => 'Wolfsspitz', 'animal_id' => '1'],
			['id' => '239', 'name' => 'Xoloitzcuintle', 'animal_id' => '1'],
			['id' => '240', 'name' => 'Yorkshire terrier', 'animal_id' => '1'],
			/*
			 * Cats
			*/
			['id' => '241', 'name' => 'Abisinio', 'animal_id' => '2'],
			['id' => '242', 'name' => 'Aphrodite\'s Giants', 'animal_id' => '2'],
			['id' => '243', 'name' => 'Australian Mist', 'animal_id' => '2'],
			['id' => '244', 'name' => 'American Curl', 'animal_id' => '2'],
			['id' => '245', 'name' => 'Azul ruso', 'animal_id' => '2'],
			['id' => '246', 'name' => 'American shorthair', 'animal_id' => '2'],
			['id' => '247', 'name' => 'American wirehair', 'animal_id' => '2'],
			['id' => '248', 'name' => 'Angora turco', 'animal_id' => '2'],
			['id' => '249', 'name' => 'Africano doméstico', 'animal_id' => '2'],
			['id' => '250', 'name' => 'Bengala', 'animal_id' => '2'],
			['id' => '251', 'name' => 'Bobtail japonés', 'animal_id' => '2'],
			['id' => '252', 'name' => 'Bombay', 'animal_id' => '2'],
			['id' => '253', 'name' => 'Bosque de Noruega', 'animal_id' => '2'],
			['id' => '254', 'name' => 'Brazilian Shorthair', 'animal_id' => '2'],
			['id' => '255', 'name' => 'Brivon de pelo corto', 'animal_id' => '2'],
			['id' => '256', 'name' => 'Brivon de pelo largo', 'animal_id' => '2'],
			['id' => '257', 'name' => 'British Shorthair', 'animal_id' => '2'],
			['id' => '258', 'name' => 'Burmés', 'animal_id' => '2'],
			['id' => '259', 'name' => 'Burmilla', 'animal_id' => '2'],
			['id' => '260', 'name' => 'Cornish rex', 'animal_id' => '2'],
			['id' => '261', 'name' => 'California Spangled', 'animal_id' => '2'],
			['id' => '262', 'name' => 'Ceylon', 'animal_id' => '2'],
			['id' => '263', 'name' => 'Cymric', 'animal_id' => '2'],
			['id' => '264', 'name' => 'Chartreux', 'animal_id' => '2'],
			['id' => '265', 'name' => 'Deutsch Langhaar', 'animal_id' => '2'],
			['id' => '266', 'name' => 'Devon rex', 'animal_id' => '2'],
			['id' => '267', 'name' => 'Dorado africano', 'animal_id' => '2'],
			['id' => '268', 'name' => 'Don Sphynx', 'animal_id' => '2'],
			['id' => '269', 'name' => 'Dragon Li', 'animal_id' => '2'],
			['id' => '270', 'name' => 'Europeo Común', 'animal_id' => '2'],
			['id' => '271', 'name' => 'Exótico de Pelo Corto', 'animal_id' => '2'],
			['id' => '272', 'name' => 'Gato europeo bicolor', 'animal_id' => '2'],
			['id' => '273', 'name' => 'FoldEx', 'animal_id' => '2'],
			['id' => '274', 'name' => 'German Rex', 'animal_id' => '2'],
			['id' => '275', 'name' => 'Habana brown', 'animal_id' => '2'],
			['id' => '276', 'name' => 'Himalayo', 'animal_id' => '2'],
			['id' => '277', 'name' => 'Korat', 'animal_id' => '2'],
			['id' => '278', 'name' => 'Khao Manee', 'animal_id' => '2'],
			['id' => '279', 'name' => 'Maine Coon', 'animal_id' => '2'],
			['id' => '280', 'name' => 'Manx', 'animal_id' => '2'],
			['id' => '281', 'name' => 'Mau egipcio', 'animal_id' => '2'],
			['id' => '282', 'name' => 'Munchkin', 'animal_id' => '2'],
			['id' => '283', 'name' => 'Ocicat', 'animal_id' => '2'],
			['id' => '284', 'name' => 'Oriental', 'animal_id' => '2'],
			['id' => '285', 'name' => 'Oriental de pelo largo', 'animal_id' => '2'],
			['id' => '286', 'name' => 'Ojos azules', 'animal_id' => '2'],
			['id' => '287', 'name' => 'PerFold1', 'animal_id' => '2'],
			['id' => '288', 'name' => 'Persa Americano o Moderno', 'animal_id' => '2'],
			['id' => '289', 'name' => 'Persa Clásico o Tradicional2', 'animal_id' => '2'],
			['id' => '290', 'name' => 'Peterbald', 'animal_id' => '2'],
			['id' => '291', 'name' => 'Pixie Bob', 'animal_id' => '2'],
			['id' => '292', 'name' => 'Ragdoll', 'animal_id' => '2'],
			['id' => '293', 'name' => 'Sagrado de Birmania', 'animal_id' => '2'],
			['id' => '294', 'name' => 'Scottish Fold', 'animal_id' => '2'],
			['id' => '295', 'name' => 'Selkirk rex', 'animal_id' => '2'],
			['id' => '296', 'name' => 'Serengeti', 'animal_id' => '2'],
			['id' => '297', 'name' => 'Seychellois', 'animal_id' => '2'],
			['id' => '298', 'name' => 'Siamés', 'animal_id' => '2'],
			['id' => '299', 'name' => 'Siamés Moderno', 'animal_id' => '2'],
			['id' => '300', 'name' => 'Siamés Tradicional', 'animal_id' => '2'],
			['id' => '301', 'name' => 'Siberiano', 'animal_id' => '2'],
			['id' => '302', 'name' => 'Snowshoe', 'animal_id' => '2'],
			['id' => '303', 'name' => 'Sphynx', 'animal_id' => '2'],
			['id' => '304', 'name' => 'Tonkinés', 'animal_id' => '2'],
			['id' => '305', 'name' => 'Van Turco', 'animal_id' => '2']
		]);
	}
}
